# Generated by Django 3.1.5 on 2021-01-29 20:49

import carpool.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('email', models.EmailField(db_index=True, max_length=255, unique=True, verbose_name='email address')),
                ('is_active', models.BooleanField(default=True)),
                ('is_admin', models.BooleanField(default=False)),
                ('first_name', models.CharField(max_length=128, verbose_name='First Name')),
                ('last_name', models.CharField(max_length=128, verbose_name='Last Name')),
                ('contact_number', models.BigIntegerField(null=True, validators=[carpool.validators.ContactNumberValidator], verbose_name='Contact Number')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Trip',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateTimeField(verbose_name='Time of Journey')),
                ('cluster', models.TextField()),
                ('travel_distance', models.FloatField()),
                ('start_place', models.TextField(blank=True, verbose_name='Starting Place')),
                ('end_place', models.TextField(blank=True, verbose_name='Ending Place')),
                ('participants', models.ManyToManyField(blank=True, related_name='participants', to='carpool.CustomUser')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hosts', to='carpool.customuser')),
            ],
        ),
    ]
