# Generated by Django 3.1.5 on 2021-01-29 20:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('carpool', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Trip',
        ),
    ]
